### ISSUE TITLE
memkind config

### ISSUE THREAD

**Issue by bcernohous** [memkind/memkind#10]
If a user application uses memkind, I’d like to know what numa node they’re mbinding. 

I see this in the man page.

       MEMKIND OPERATIONS:
       The memkind_ops structure is a vtable that defines the operations which
       determine the kind of memory.  This design pattern is modeled after the
       "mix-in"  pattern  used  in the Linux kernel to enable some of the fea-
       tures of an object oriented language in C.  This  section  defines  the
       inputs, outputs and responsiblities of each function pointer enumerated
       in the memkind_ops structure.  Each of these methods takes a  memkind_t
       argument  as  its  first parameter which shall be self referencing.  In
       this documentation the function pointers in the  memkind_ops  structure
       will  be  prepended with "ops."  and should be considered the operation
       associated with the kind.

       int  ops.get_mbind_nodemask(memkind_t  kind,  unsigned  long *nodemask,
       unsigned long maxnode);
       shall set the nodemask of length maxnode bits to  a  value  appropriate
       for passing to the mbind(2) system call for the kind.

So is something along these lines a reasonable, and supported, way to get the HBW nodemask from the underlying memkind configuration? (Not sure I want to use the kind or an ops table directly).

       ret = MEMKIND_HBW->ops->get_mbind_nodemask(MEMKIND_HBW, &nodemask, NUMA_NUM_NODES);

       ret = MEMKIND_HBW_HUGETLB_OPS.get_mbind_nodemask(kind, &nodemask, maxnode);

**Comment by cmcantalupo** [comment]
I would recommend using the kind rather than the ops table, since the kind must be passed to the API as the first argument:

ret = MEMKIND_HBW->ops->get_mbind_nodemask(MEMKIND_HBW, &nodemask, NUMA_NUM_NODES);

This is both reasonable and supported.  You may also just use the API documented in the memkind_hbw.3 man page:

int memkind_hbw_get_mbind_nodemask(struct memkind *kind, unsigned long *nodemask, unsigned long maxnode);

which is what the ops table points to.  If you are specifically interested in the mask used by a particular kind the former is better.

**Comment by bcernohous** [comment]
Thanks.  I missed that API.
