### ISSUE TITLE
memkind_pmem forking support

### ISSUE THREAD

**Issue by JohnSully** [memkind/memkind#224]
In KeyDB I achieve this with btrfs snapshots to copy the COW behavior that happens with normal memory.  To do so it requires looping through each pach and remapping to a different fd.  (It also requires exposing the fd externally to permit the snapshot creation). 

I've seen other ways of doing this by remapping each page as private and the kernel will COW to normal RAM instead which is another great option depending on how much the two processes will diverge.

It would be great to have official support for this so I don't have to maintain a forked version.  I think fork() is pretty common so it would be something others would want as well.

**Comment by pbalcer** [comment]
In our other memory allocator for volatile PMEM, libvmmalloc, we implemented `fork` with a configuration option, see:
https://github.com/pmem/pmdk/blob/master/doc/libvmmalloc/libvmmalloc.7.md

But there are some caveats that make both approaches IMHO unusable for an in-memory database.
Remapping as private will work, but you won't be able to get back to shared mappings in the parent even after the spawned processes go away (doing so would require us to copy all the DRAM pages back to the file). Cloning the pool on fork could work, but that would cause extremely high tail latency and would cause a spike in traffic to PMEM. Using reflink with btrfs/xfs might help.

**Comment by JohnSully** [comment]
What I'm currently doing is creating brtfs snapshots with FICLONE and then remapping the extents to this new file in the child process.  To do so I had to break encapsulation and provide APIs to both expose and swap out fd's.

**Comment by jschmieg** [comment]
We plan adding to Memkind support to KMEM DAX (first PRs with this are https://github.com/memkind/memkind/pull/220 and https://github.com/memkind/memkind/pull/223). This is static PM kind created on PM exposed as NUMA node with MAP_PRIVATE mapping. This kind natively supports CoW on PM, by placing modified pages on the same NUMA node as original ones. 
Some details about exposing PM as NUMA can be found here: https://lwn.net/Articles/777212/.

**Comment by JohnSully** [comment]
@jschmieg Thanks for letting me know about your NUMA driver. I have been looking for a way to force the *entire* process to use file backed memory for all data pages. It looks like that might be a good way to do it. An extra NUMA node is brilliant.

**Comment by pbalcer** [comment]
@JohnSully if you don't mind me asking, what's your current approach for PMEM support in KeyDB? I'm assuming that's why you are requesting fork support.

We (PMDK/Memkind group at Intel) have done intensive research into what's the best way of implementing redis RDB-style persistence with persistent memory, and came to the conclusion that we shouldn't rely on the OS copy-on-write because performance will suffers significantly. There are two primary reasons for that: a) CoW works on page granularity, causing potentially significant write-amplification for some data structures - this is especially important in the case of bandwidth constrained medium such as Intel® Optane™ DC Persistent Memory. 2) CoW will break-up huge-pages into 4k pages, which on its own reduces performance. Additionally, in the case of redis, RDB pretty much prevents huge pages from being used, meaning that for large redis instances we might see a significant amount of TLB misses and overhead for page metadata.
For these reasons, we've created a prototype of Redis that implemented copy-on-write for individual data structures, and we've observed *significantly* better performance.
This work lives in https://github.com/pmem/redis.

**Comment by JohnSully** [comment]
Hi Piotr,

Thanks for the information. I’m using memkind for multiple things right now so my questions/comments aren’t all pmem related. COW is used more with FLASH although perf is a major problem so still. 

I am looking at NVDIMMs but more for durable storage. The price improvements vs DRAM haven’t materialized yet - so I’m not looking at using it for the volatile use case. 

By the way I’ve decided to look into a different programming model for the NV case that still uses memkind. Rearchitecting around the PMDK isn’t appealing - especially when the hardware is still niche.

**Comment by pbalcer** [comment]
Are you planning on using memory-mapped I/O to extend the database with flash memory? I'm not sure if that's going to perform well. What you will be effectively building is a DRAM cache (in-memory key/values) on top of another DRAM cache (page cache from the OS) that's backed by the SSD. These two caches will compete with each other for memory, and eventually the page cache will get starved out and the database will be constantly swapping pages in and out of DRAM.

Why do you say that the price improvements haven't materialized for PMEM? The hardware *is* less expensive than DRAM (see https://www.tomshardware.com/news/intel-optane-dimm-pricing-performance,39007.html). Another advantage is density.

I agree that there's more value and opportunity for streamlining of deployments in the persistent use case, but, as you've noticed, the programming model can be challenging. That's why we've developed things like memkind, so that applications can the easy thing first (volatile) and leverage persistence later.

How are you planning on using memkind with persistence? Are you planning on reusing the heap file across restarts? To accomplish that, you'd need very extensive changes in jemalloc to make sure that all of its internal data structures are also located in that file (which would make the allocator slower). And even if you could do that, you would only be able to restart the heap if it was shutdown gracefully. Also, you'd have to be careful that all pointers from the pmem heap are assigned somewhere reachable.

**Comment by JohnSully** [comment]
Re the pricing, the trouble is when you actually go to buy them you find they aren't sold at list price.  Ultimately the issue is the hardware is still quite exotic, but I have no doubt that will improve over time (which is why I'm looking to supporting it).

I'm not quite ready to talk about the exact approach we're taking yet (still in development) but I've made a few changes to your pmem kernel driver as well so its not quite what your expecting :).  You are correct that there are issues with jemalloc using anonymous memory even when file backed.

**Comment by michalbiesek** [comment]
@JohnSully 
Regarding support for COW in PM which was already mentioned in this thread - it is now available 
as MEMKIND_DAX_KMEM kind -in release https://github.com/memkind/memkind/releases/tag/v1.10.0

 For configuration details see "Device DAX" section in Readme
