### ISSUE TITLE
How to install memkind to include internal header files?

### ISSUE THREAD

**Issue by hesuyouren** [memkind/memkind#531]
I would like to include memkind_pmem.h, what should I do to install the proj (i.e. in developer mode)?

**Comment by michalbiesek** [comment]
We remove internal header files from installing it - see https://github.com/memkind/memkind/issues/226 - the internal header files are excluded since the internal implementation could be changed. For integration in the project, we provide interfaces mentioned in https://github.com/memkind/memkind#interfaces

**Comment by hesuyouren** [comment]
Thanks for the reply! I would like to know if there is a way I can make the backing file of pmem_kind visible in the pmem_dir I set and name the file by myself as well (I tried to call memkind_pmem_mmap() but you said the api interface was removed). Thanks again!

**Comment by michalbiesek** [comment]
Hi,

Let me clarify my previous message - we don't want to install internal headers to provide our internal implementation interface. Internal implementation **could** be changed, and we don't want to constraint with backward compatibility for internal interfaces in the future.

Memkind is a heap manager responsible for heap allocation and _creating_/_destroying_ heaps. Regarding the PMEM scenario based on FS-DAX: under the hood, we _create_ and _destroy_ file placed on PMEM using memkind API.

Regarding visibility of file: we perform unlink operations on the file since we support volatile usage of PMEM. The unlink operation is here:
https://github.com/memkind/memkind/blob/be54c08318e036ab1fea0dc92ca9d61a7e2ac1e3/src/memkind_pmem.c#L227

**Comment by lukaszstolarczuk** [comment]
It seems this issue is resolved, if you have any more questions, please file a new issue.
